export const BASE_TILE_COLORS = [
  'lightcoral',
  'lemonchiffon',
  'peachpuff',
  'palegreen',
  'paleturquoise',
  'lavender',
  'honeydew',
  'mistyrose',
  'azure',
  'ghostwhite',
  'lavenderblush',
  'lightpink',
  'thistle',
  'powderblue',
  'mediumslateblue',
  'aquamarine',
  'greenyellow',
  'lightgreen',
  'papayawhip',
  'coral',
  'salmon',
];

export const ACTIVE_TILE_COLORS = [
  'darkviolet',
  'orangered',
  'crimson',
  'gold',
  'chartreuse',
  'turquoise',
  'mediumblue',
  'deeppink',
];
